matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
      script:
        - npm i -g pkg
        - npm run build-darwin
cache:
  directories:
    - node_modules

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
  only:
    - master