matrix:
  include:
    - os: osx
      osx_image: xcode10.8
      language: node_js
      node_js: "10"
      script:
        - npm i -g pkg
        - npm run build-darwin

cache:
  directories:
    - node_modules
    
branches:
  only:
    - master