matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "11"
      before_script:
        - export NODE_OPTIONS=–-max_old_space_size=8192
      script:
        - npm i -g pkg
        - npm run build-darwin

cache:
  directories:
    - node_modules

branches:
  only:
    - master