matrix:
  include:
    - os: osx
      language: node_js
      node_js: "10"
      script:
        - npm i -g pkg
        - npm run build-darwin
cache:
  directories:
    - node_modules

branches:
  only:
    - master