matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12.0.8"
      script:
        - npm i -g pkg
        - npm run build-darwin
cache:
  directories:
    - node_modules

branches:
  only:
    - master