os:
  - linux
  - osx
language: node_js
node_js:
  - 9
  - "node"
cache: npm
matrix:
  exclude:
    - os: linux
      node_js: 10
  include:
    - os: osx
      node_js: 9
      script: npm i -g pkg
      script: npm run compile-darwin