language: node_js
sudo: true
os: osx

node_js:
  - 10

install:
  - npm i --ignore-scripts

before_script:
#  MacOS 64 bits version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list cmake &>/dev/null || brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list automake &>/dev/null || brew install automake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list libtool &>/dev/null || brew install libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list pkg-config &>/dev/null || brew install pkg-config; fi

script:
  # Compiles switch service
  - cd ./node_modules/node-window-manager && npm run rebuild
  - cd ./node_modules/iohook && npm run build
  - npm install -g pkg
  - npm run build-darwin

branches:
  only:
    - master