matrix:
  include:
    - os: osx
      osx_image: xcode10.8
      language: node_js
      node_js: "10"
      env:
        - NODE_OPTIONS=–-max_old_space_size=4096
      before_script:
        - export NODE_OPTIONS=–-max_old_space_size=4096
      script:
        - npm i -g pkg
        - npm run build-darwin

cache:
  directories:
    - node_modules
    

branches:
  only:
    - master