image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm i
  - npm i -g pkg

build_script:
  - npm run build-win32

test: off

branches:
  only:
    - master