image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm i
  - npm i -g pkg

build_script:
  - npm run build-win32

test: off

branches:
  only:
    - master

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $GH_TOKEN # your encrypted token from GitHub
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true