image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm i

build_script:
  - npm i -g pkg
  - npm run build-win32

test: off

branches:
  only:
    - master